# Generated by Django 6.0.3 on 2026-03-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.TextField()),
                ('targetUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('type', models.CharField(default='image', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
