# Generated by Django 6.0.3 on 2026-03-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='videoBase64',
            new_name='videoUrl',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='authorProfilePicture',
        ),
        migrations.RemoveField(
            model_name='review',
            name='userProfilePicture',
        ),
    ]
