# Generated by Django 6.0.3 on 2026-03-26 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_videobase64_property_videourl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceType', models.CharField(max_length=100)),
                ('pickupAddress', models.CharField(max_length=255)),
                ('destinationAddress', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contactPhone', models.CharField(max_length=30)),
                ('city', models.CharField(default='Ouagadougou', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleModel', models.CharField(max_length=255)),
                ('vehicleCompanyName', models.CharField(max_length=255)),
                ('userName', models.CharField(max_length=255)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPhone', models.CharField(blank=True, max_length=30, null=True)),
                ('numberOfDays', models.IntegerField(default=1)),
                ('withDriver', models.BooleanField(default=False)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cnibImage', models.TextField(blank=True, null=True)),
                ('cnibBackImage', models.TextField(blank=True, null=True)),
                ('licenseImage', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='pending', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_reservations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reservations', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.vehicle')),
            ],
        ),
    ]
