# Generated by Django 6.0.3 on 2026-03-26 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='likedBy',
            field=models.ManyToManyField(blank=True, related_name='liked_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
