# Generated by Django 6.0.3 on 2026-03-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_property_likedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='imageUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
