// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEbQCLSZOe8GxhO9gp_4G8T-wpdJEO7qg',
    appId: '1:704257001092:web:aeaefc19f6aa9adc8324d1',
    messagingSenderId: '704257001092',
    projectId: 'imobareld',
    authDomain: 'imobareld.firebaseapp.com',
    storageBucket: 'imobareld.firebasestorage.app',
    measurementId: 'G-3X1YF4HDHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxK9W30o07Jz5KJGCbl51tuyexo8ihpUI',
    appId: '1:704257001092:android:d6222908c3e2bc038324d1',
    messagingSenderId: '704257001092',
    projectId: 'imobareld',
    storageBucket: 'imobareld.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd2tYOeUDSry91a6o9BZsuqfXdI_kDBlw',
    appId: '1:704257001092:ios:35a32c6b50d0cfae8324d1',
    messagingSenderId: '704257001092',
    projectId: 'imobareld',
    storageBucket: 'imobareld.firebasestorage.app',
    iosBundleId: 'app.imobareld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd2tYOeUDSry91a6o9BZsuqfXdI_kDBlw',
    appId: '1:704257001092:ios:35a32c6b50d0cfae8324d1',
    messagingSenderId: '704257001092',
    projectId: 'imobareld',
    storageBucket: 'imobareld.firebasestorage.app',
    iosBundleId: 'app.imobareld',
  );
}
