/// Constantes géographiques pour le Burkina Faso.
/// Contient toutes les villes et leurs quartiers/zones respectifs.
class BfLocations {
  BfLocations._();

  /// Retourne les quartiers d'une ville donnée.
  /// Retourne une liste vide si la ville n'est pas trouvée.
  static List<String> quartiersOf(String city) {
    return _locations[city] ?? [];
  }

  /// Toutes les villes disponibles dans l'application.
  static List<String> get cities => _locations.keys.toList();

  /// Map principale : Ville → Liste de Quartiers/Zones
  static const Map<String, List<String>> _locations = {
    'Ouagadougou': [
      'Baskuy (Centre)',
      'Bogodogo',
      'Boulmiougou',
      'Nongremassom',
      'Sig-Noghin',
      // Quartiers populaires de Ouaga
      'Ouaga 2000',
      'Gounghin',
      'Koulouba',
      'Patte d\'Oie',
      'Cissin',
      'Dassasgho',
      'Pissy',
      'Dapoya',
      'Tampouy',
      'Zogona',
      'Tanghin',
      'Somgandé',
      'Kilwin',
      'Wayalghin',
      'Wemtenga',
      'Zone du Bois',
      'Karpala',
      'Balkuy',
      'Bassinko',
      'Bonheur-Ville',
      'Nioko I',
      'Nioko II',
      'Rimkieta',
      'Kamboinsé',
      'Kossodo',
      'Saaba',
      'Silmiougou',
    ],
    'Bobo-Dioulasso': [
      'Secteur 1 (Dafra)',
      'Secteur 2 (Dafra)',
      'Secteur 3 (Dafra)',
      'Secteur 4 (Dafra)',
      'Secteur 1 (Konsa)',
      'Secteur 2 (Konsa)',
      'Secteur 3 (Konsa)',
      'Secteur 4 (Konsa)',
      'Secteur 1 (Do)',
      'Secteur 2 (Do)',
      'Secteur 3 (Do)',
      'Secteur 4 (Do)',
      'Dioulassoba',
      'Colsama',
      'Accart-Ville',
      'Hamdallaye',
      'Kôkô',
      'Sarfalao',
      'Bindougousso',
      'Sikasso-Cira',
      'Bolomakoté',
      'Ouezzinville',
    ],
    'Koudougou': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
      'Secteur 6',
      'Secteur 7',
      'Secteur 8',
      'Secteur 9',
      'Secteur 10',
      'Secteur 11',
      'Secteur 12',
    ],
    'Ouahigouya': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
      'Secteur 6',
      'Secteur 7',
      'Secteur 8',
      'Secteur 9',
      'Secteur 10',
      'Secteur 11',
    ],
    'Banfora': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
      'Secteur 6',
      'Secteur 7',
      'Secteur 8',
      'Secteur 9',
    ],
    'Dédougou': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
      'Secteur 6',
      'Secteur 7',
    ],
    'Fada N\'Gourma': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
      'Secteur 6',
      'Secteur 7',
      'Secteur 8',
    ],
    'Kaya': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
      'Secteur 6',
      'Secteur 7',
      'Secteur 8',
    ],
    'Manga': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Ziniaré': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
    ],
    'Tenkodogo': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
      'Secteur 6',
    ],
    'Réo': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
    ],
    'Kongoussi': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
    ],
    'Léo': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
    ],
    'Diébougou': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
    ],
    'Gaoua': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Tougan': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
    ],
    'Nouna': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
    ],
    'Zorgo': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
    ],
    'Pouytenga': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
    ],
    'Dori': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
    ],
    'Pô': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Gorom-Gorom': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
    ],
    'Djibo': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
    ],
    'Boulsa': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
    ],
    'Boromo': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
    ],
    'Houndé': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Batié': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
    ],
    'Diapaga': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
    ],
    'Yako': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Toma': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Pama': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Dano': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Orodara': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Sindou': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Garango': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Niangoloko': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Gourcy': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Solenzo': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Ouargaye': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Sapouy': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Bogandé': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Gayéri': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Koupéla': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Kombissiri': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Boussé': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Titao': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Sébba': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
    'Bittou': [
      'Secteur 1',
      'Secteur 2',
      'Secteur 3',
      'Secteur 4',
      'Secteur 5',
    ],
  };
}
